version: '3'

services:
  app:
    build:
      context: .
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}:latest
          - ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./app/index.mjs:/app/index.mjs
      - ./app/entrypoint.sh:/app/entrypoint.sh
      - ./app/state.json:/app/state.json
      - ./app/commands.json:/app/commands.json
      - ./app/history:/app/history
